### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gnilk**
Added compactPreviewTime to control rendering of preview time string.

A boolean controlling the construction of the time-preview string. False (default) leaves it as today. True removes any space around ‘:’.
Example: 
  False: “10 : 42”
  True: “10:42”

This makes rendering more compact especially when using larger fonts.

### CODE REVIEW

**Comment by gnilk** [comment]
Eh, something might have gone wrong here. There should not be two commits. Not sure why this is.

**Comment by ecmadao** [comment]
It seems has a wrong commit which delete some test files, but it's okey.

So, you need a different time format, more compactly, right? And I think using the `compactPreviewTime ` props is not the best way to deal this situation. Maybe we can add a new props like 'timeFormatter', or something like this, it can receive a string or a function. Then we can render time ui style by using this props, like `timeFormatter={'HH:MM'}` or `timeFormatter={'HH : MM'}` or even `timeFormatter={(hour, minute) => `hour&minute`}`

How do you think about it? @gnilk

**Comment by gnilk** [comment]
That would be much better. I considered it but thought the logical impact and change of behavior was too big/invasive to I settled for the simpler solution. All in favor for such a solution. 

I would prefer the callback method, that way it is possible to style the time-format the way the application likes it (in my case the time and date formatting would be consistent throughout the application and controlled by the user).

**Comment by ecmadao** [comment]
Cool! So I have to close your PR, and I'll working on this new feature tonight.

**Comment by ecmadao** [comment]
The new version v2.2.4 published, add `timeFormat` and `timeFormatter` props. You can check README or test case for more usage detail. @gnilk

**Pull request closed without merging**
