### PR TITLE
Finished fully connecting the onTimezoneChange callback function to t…

### PR DESCRIPTION
**Pull request by erin-doyle**
…he TimezonePicker

### CODE REVIEW

**Comment by ecmadao** [comment]
Cool. Merged.

**Comment by ecmadao** [comment]
@erin-doyle 
hi, Sorry to say that. I find a bug here in this PR.
In `TimePicker.jsx`, you do this `const timeData = timeHelper.time(time, meridiem, timeMode, timezone);` to format `time` props and put it to state, then render UI with `timeData` in state, right? But after dragged or clicked an hour or minute, cause you didn't update `timeData` in state, then the UI won't change.

Actually, I think we don't need to store `time` props, it should be passed by outside.

**Comment by ecmadao** [comment]
@erin-doyle 
But cause user's timezone almost won't change, it's ok to get it and store in state. I'll fix this problem and publish a new version.

**Comment by ecmadao** [comment]
Fixed. And new version v2.1.3 published.

**Comment by erin-doyle** [comment]
Awesome, thanks for catching that @ecmadao !

**Pull request merged**
